name: Firebase function deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up Node.js version 18.x (or higher)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup .npmrc for GitHub Packages
      - name: Setup .npmrc file for GitHub Packages
        run: |
          echo "@your-scope:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.RISEFUNDS_BENEDICT_PAT }}" >> ~/.npmrc

      # Install npm packages inside the functions directory
      - name: Install npm packages
        working-directory: functions
        run: npm install

      # Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy Firebase functions using Firebase CLI
      - name: Deploy to Firebase
        run: firebase deploy --only functions --project risefunds --debug
