name: Firebase function deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up Node.js version 18.x
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Checkout the repository
      - uses: actions/checkout@v3

      # Authenticate with GitHub Packages by setting up the .npmrc file
      - name: Setup .npmrc file for GitHub Packages
        run: |
          echo "@risefunds:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.RISEFUNDS_BENEDICT_PAT }}" >> ~/.npmrc

      # Install npm packages inside the functions directory
      - name: Install npm packages
        working-directory: functions
        run: npm install

      # Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Decode the Base64-encoded service account key
      - name: Decode Service Account Key
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > ${{ runner.temp }}/gcloud-service-key.json

      # Debug: Check if service account file is saved correctly
      - name: Check Service Account File
        run: cat ${{ runner.temp }}/gcloud-service-key.json

      # Deploy Firebase functions using Firebase CLI
      - name: Deploy to Firebase
        run: firebase deploy --only functions --project risefunds --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud-service-key.json
