name: Firebase function deploy

on:
  push:
    branches: [prod]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Create .npmrc file to authenticate with GitHub Packages
      - name: Setup .npmrc file for GitHub Packages
        run: |
          echo "@risefunds:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.RISEFUNDS_BENEDICT_PAT }}" >> ~/.npmrc

      # Install npm packages
      - name: Install npm packages
        run: |
          cd functions
          npm install

      # Run ESLint with the --fix flag to automatically fix issues
      - name: Run ESLint to fix issues
        run: |
          cd functions
          npm run lint -- --fix

      # Deploy to Firebase after fixing lint errors
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
