name: Firebase function deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up Node.js version 18.x (or higher)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Specify Node.js version >= 18

      # Checkout the repository
      - uses: actions/checkout@v3

      # Authenticate with GitHub Packages by setting up the .npmrc file
      - name: Setup .npmrc file for GitHub Packages
        run: |
          echo "@risefunds:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.RISEFUNDS_BENEDICT_PAT }}" >> ~/.npmrc

      # Install npm packages inside the functions directory
      - name: Install npm packages
        working-directory: functions
        run: npm install

      # Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Run ESLint with the --fix flag to automatically fix issues
      - name: Run ESLint to fix issues
        working-directory: functions
        run: npm run lint -- --fix

      # Set up Service Account for authentication
      - name: Setup Google Application Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ${HOME}/gcloud-service-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Print Google Application Credentials
        run: cat ${HOME}/gcloud-service-key.json

      - name: Set Firebase project
        run: firebase use --risefunds

      # Debug: Check if service account file is saved correctly
      - name: Check Service Account File
        run: ls -la ${HOME}/gcloud-service-key.json

      # Deploy Firebase functions using Firebase CLI
      - name: Deploy to Firebase
        run: firebase deploy --only functions --project risefunds --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/gcloud-service-key.json
