name: Firebase function deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Node.js version 18.x (or higher)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Step 2: Checkout the repository
      - uses: actions/checkout@v3

      # Step 3: Set up .npmrc file for GitHub Packages authentication
      - name: Setup .npmrc file for GitHub Packages
        run: |
          echo "@risefunds:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.RISEFUNDS_BENEDICT_PAT }}" >> ~/.npmrc

      # Step 4: Install npm packages inside the functions directory
      - name: Install npm packages
        working-directory: functions
        run: npm install

      # Step 5: Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 6: Set up Service Account by saving raw JSON to a file
      # We create the service account file dynamically in the runner
      - name: Setup Google Application Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ${{ github.workspace }}/gcloud-service-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Step 7: Debug - Check if the Service Account JSON is saved correctly
      - name: Check Service Account File
        run: cat ${{ github.workspace }}/gcloud-service-key.json

      - name: Print Google Application Credentials
        run: cat ${{ github.workspace }}/gcloud-service-key.json

      # Step 8: Deploy Firebase functions using Firebase CLI
      - name: Deploy to Firebase
        run: firebase deploy --only functions --project risefunds --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-service-key.json
