name: Firebase function deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set up Node.js version 18.x (or higher)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Checkout the repository
      - uses: actions/checkout@v3

      # Install npm packages inside the functions directory
      - name: Install npm packages
        working-directory: functions
        run: npm install

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Set up Service Account for authentication
      - name: Setup Google Application Credentials
        run: |
          echo "${{ secrets.FB_SERVICE_JSON }}" > ${HOME}/gcloud-service-key.json
        env:
          FB_SERVICE_JSON: ${{ secrets.FB_SERVICE_JSON }}

      # Deploy Firebase functions using Firebase CLI
      - name: Deploy to Firebase
        run: firebase deploy --only functions
        env:
          FB_SERVICE_JSON: ${HOME}/gcloud-service-key.json
